### ISSUE TITLE
purchase order log

### ISSUE THREAD

**Issue by lgastmans** [quentindecosne/sunlit#101]

**Comment by quentindecosne** [comment]
@lgastmans do we want a detailed log or just a simple one

detailed would be

- Bob created the draft order on the 1st of July
- Bob added 500 x Inverter 4kW @ $1,500
- Kumar change the quantity of Inverter 4kW to 250
- Kumar change the price of Inverter 4kW to $2,000
- Bob placed the order on the 4th of July
- Bob confirmed the order on the 5th of July
- Kumar marked the order as Shipped by DHL with tracking number XXXX-XX-XXX on the 10th of July,

simple would be
- Bob created the order on the 1st of July
- Bob placed the order on the 4th of July
- Bob confirmed the order on the 5th of July
- Kumar marked the order as shipped on the 10th of July

What do you think?
