### ISSUE TITLE
Review the price format across the app

### ISSUE THREAD

**Issue by quentindecosne** [quentindecosne/sunlit#130]
Make sure all the prices are displayed using the same format

There might be a way to do it globally rather than in each view

**Comment by quentindecosne** [comment]
@lgastmans you've been using 
```php
$fmt = new NumberFormatter($locale = 'en_IN', NumberFormatter::CURRENCY);
```
but that creates an issue when using those numbers to do some calculations.

**Comment by lgastmans** [comment]
but do I use those in a mutator / accessor? 
I thought I only use it in the getListforDatatables...

**Comment by quentindecosne** [comment]
You only use it in the getListForDatatables but my issue was that it has to be consistent, if we display some price as
Rs. xxx,xxx.xx and others as Rs. xxxxxx.xx that's not good or?

**Comment by quentindecosne** [comment]
we'll see when they ask
