### ISSUE TITLE
Top Right logged in User

### ISSUE THREAD

**Issue by lgastmans** [quentindecosne/sunlit#15]
The correct name of the user logged in should be displayed in the top right corner

**Comment by quentindecosne** [comment]
closes #15

**Comment by quentindecosne** [comment]
Closed https://github.com/quentindecosne/sunlit/commit/09728197be7c5344f328f42d9f4124cb49430552

**Comment by quentindecosne** [comment]
close https://github.com/quentindecosne/sunlit/commit/09728197be7c5344f328f42d9f4124cb49430552
