### ISSUE TITLE
global search field as session variable?

### ISSUE THREAD

**Issue by lgastmans** [quentindecosne/sunlit#156]
The global search fields of the grids could be a session variable?
For example: filter on a column in products, like supplier name, edit a row, come back to the view with the filter still active...

**Comment by quentindecosne** [comment]
Instead of 
```php
return redirect(route('products'))->with('success', trans('app.record_edited', ['field' => 'product']));
```

Maybe we should do this
```php
return back()->withInput();
```

And if we want to notification, we need to add the 
```php
 ->with('success'...)
 ```

**To be tested...**
