### ISSUE TITLE
Soft delete and unique index

### ISSUE THREAD

**Issue by quentindecosne** [quentindecosne/sunlit#17]
We are using soft deletes for the categories (and probably other models) and an issue came up.
If we delete a category from the index view, it disappear and a deleted_at is set in the table.
This is all good, except that if you try to add a category with the same name, because it's then not unique, it fails.

What do we want to do about it?

**Don't use soft deletes**
I think it's practical to have them even just for select box

**Don't use the word delete but disable and still show the disabled ones in the datatable**
For category it might not be an issue but for products, we might end up with 100s of disabled products

**Remove the unique attribute**
If a category is deleted, it shouldn't be an issue if another one is added with the same name, the deleted one wouldn't show anywhere, maybe in reports?

What do you think? do you see any other options

**Comment by lgastmans** [comment]
unique index on name + deleted_at?

**Comment by quentindecosne** [comment]
add this to validation requests 

`  'name' => 'required|max:255|unique:categories,name,NULL,id,deleted_at,NULL'.$this->id,`

**Comment by quentindecosne** [comment]
this needs to be applied to all validations using softdeletes:

- [ ] categories
- [ ] dealers
- [ ] products
- [ ] states
- [ ] suppliers
- [ ] taxes
- [ ] users
