### ISSUE TITLE
PDF export option

### ISSUE THREAD

**Issue by lgastmans** [quentindecosne/sunlit#172]
- [ ] inventory
- [ ] sale order
- [ ] purchase order
- [ ] purchase order invoice
- [ ] products
- [ ] suppliers
- [ ] dealers
- [ ] warehouse

**Comment by quentindecosne** [comment]
Have a look at https://github.com/barryvdh/laravel-dompdf

**Comment by quentindecosne** [comment]
see https://github.com/quentindecosne/sunlit/commit/dda8daec055fbad0af35c6bd5b35b3814d78556b

**Comment by quentindecosne** [comment]
https://datatables.net/extensions/buttons
https://datatables.net/extensions/buttons/examples/styling/bootstrap5.html

**Comment by quentindecosne** [comment]
this will be done with https://github.com/quentindecosne/sunlit/issues/331
