### ISSUE TITLE
Modify the custom amount calculation 

### ISSUE THREAD

**Issue by quentindecosne** [quentindecosne/sunlit#305]
CD is on products/categories and not on the invoice

the BOE cost should match the landed cost

**Comment by quentindecosne** [comment]
I've moved the customs duty, social welfare, and igst to the invoice item table.
I save the % in a JSON field and I calculate the USD amount for each which I save in the item table.

When clearing the invoice from custom I calculate the INR and display them in the sidebar, they are also saved in the invoice table just in case.

@lgastmans can you test this?

**Comment by lgastmans** [comment]
From what I understood from the file they sent "Solar Edge calculation" (in documents folder) the changes were:
1. Landed cost is based on Supplier Amount, and not on Customs Amount
2. IGST is not included
3. Question: I think Rishi told us that the Transportation & Bank Charges had to left out, but in this file it is there... need to clarify with them
