### ISSUE TITLE
Review layout for smaller screen 

### ISSUE THREAD

**Issue by lgastmans** [quentindecosne/sunlit#331]
Index datatables
- [x] inventory
- [x] sale order
- [x] purchase order
- [x] purchase order invoice
- [x] products
- [x] suppliers
- [x] dealers
- [x] warehouse
- [x] settings
- [x] taxes
- [x] categories
- [x] users

Show/Cart pages
- [x] Product
- [x] Warehouse
- [ ] Purchase Order
- [ ] Purchase Order Invoice
- [ ] Sale Order

**Comment by quentindecosne** [comment]
https://datatables.net/extensions/buttons/examples/column_visibility/columns.html
https://datatables.net/extensions/buttons/examples/styling/bootstrap5.html
