### ISSUE TITLE
Update suppliers table

### ISSUE THREAD

**Issue by quentindecosne** [quentindecosne/sunlit#4]
We need to have country in there, that means another table for the country.

Make/update migration

- [x] Allow null for:

- state_id
- district _(I don't think it's needed for the suppliers)_
- gstin
- phone2

- [x] Rename company_title to company

- [x] Rename zip to zip_code

Should we have address and address2

**Comment by lgastmans** [comment]
I also set nullable for two other fields (email and contact_person)
