### ISSUE TITLE
Dealers (or Dashboard?): graph for sales per KW rating. Quaterly and monthly

### ISSUE THREAD

**Issue by lgastmans** [quentindecosne/sunlit#410]

**Comment by quentindecosne** [comment]
@lgastmans which kind of graph do we want:

<img width="676" alt="image" src="https://user-images.githubusercontent.com/17610084/199985516-c703bc41-f069-490b-8c5e-08f5924462bf.png">

<img width="679" alt="image" src="https://user-images.githubusercontent.com/17610084/199985817-2319410f-78bd-492e-acaf-c1c0ec8eb2de.png">

<img width="648" alt="image" src="https://user-images.githubusercontent.com/17610084/199985938-56af310b-b54d-4f6f-ae2e-76232fe2ca8d.png">

<img width="664" alt="image" src="https://user-images.githubusercontent.com/17610084/199986016-db594ce7-4d4d-4bf5-8a39-26f82936361f.png">
