### ISSUE TITLE
Suppliers state_id should not be required

### ISSUE THREAD

**Issue by lgastmans** [quentindecosne/sunlit#60]
Suppliers state_id should not be required

**Comment by quentindecosne** [comment]
It shouldn't but you can do conditional validation with laravel, so if you really want to you can

**Comment by lgastmans** [comment]
@quentindecosne : I did not close this issue because I thought that maybe we should make the email address also nullable (not required) ? But it had the soft-delete code in the StoreSupplierRequest, so was not sure what to do.

If you think it should be required then you can close the issue
